name: Backend - Tests y Coverage

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test-backend:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: eventos-backend

    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_USER: eventos_app_user
          POSTGRES_PASSWORD: eventos_app_pass
          POSTGRES_DB: eventos_db
        ports:
          - "5432:5432"
        options: >-
          --health-cmd="pg_isready -U eventos_app_user -d eventos_db"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    env:
      NODE_ENV: test
      JWT_SECRET: super-secret-ci

      DB_HOST: localhost
      DB_PORT: 5432
      DB_USER: eventos_app_user
      DB_PASSWORD: eventos_app_pass
      DB_NAME: eventos_db

      PGHOST: localhost
      PGPORT: 5432
      PGUSER: eventos_app_user
      PGPASSWORD: eventos_app_pass
      PGDATABASE: eventos_db

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: npm
          cache-dependency-path: eventos-backend/package-lock.json

      - name: Install backend deps
        run: npm ci

      - name: Wait for PostgreSQL
        run: |
          echo "Esperando a que Postgres est√© listo..."
          for i in {1..10}; do
            pg_isready -h localhost -p 5432 -U eventos_app_user -d eventos_db && break
            sleep 2
          done

      - name: Run tests with coverage
        run: npm test -- --coverage
